# Site config
# ---------------------------------------------------------------

# Title on top left of menu. Leave empty to use main blog title
menu_title: 

# URL of the Home page image
index_cover: /img/home-bg.jpg

# Set your own favicon
favicon: /img/favicon.png

logo: /img/flogo.png

# Site start year
# Default with current year
start_year: 2020

# Post config
# ---------------------------------------------------------------

# Default post title
default_post_title: Untitled

# Enable post toc
toc: true

# Post meta
post_info:
  word_count: true
  read_time: true

# Enable post mathjax render
mathjax:
  enable: false
  cdn: //cdn.jsdelivr.net/npm/mathjax@2.7.5/unpacked/MathJax.js?config=TeX-AMS-MML_HTMLorMML

# Comments. Choose one by filling up the information
comments:
  # Disqus comments
  disqus:
    enable: false
    shortname: 
  # Gitalk
  gitalk:
    enable: false
    owner:
    repo:
    oauth:
      accessToken:
      clientId:
      clientSecret:
    admin:

# Footer config
# ---------------------------------------------------------------
footer:
  author:
  menu:
    Home: /
    Archives: /archives
    Tags: /tags
  social_link:
    twitter_url: https://twitter.com/therohitdas
    twitter_handle: TheRohitDas
    facebook_url: 
    github_url: https://github.com/therohitdas
    gitlab_url: 
    linkedin_url: https://www.linkedin.com/in/therohitdas/
    mailto: 

# Tracking config
# ---------------------------------------------------------------

# Google Analytics Tracking ID
google_analytics:

# Busuanzi Statistics
busuanzi:
  enable: false
  cdn: //busuanzi.ibruce.info/busuanzi/2.3/busuanzi.pure.mini.js
  site_views: false
  site_visitors: false
  post_views: false